using System.Runtime.InteropServices;
using Kivi.Core.Abstractions;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.System.Threading;
using Windows.Win32.UI.Accessibility;

namespace Kivi.Platform.Context;

/// <summary>
/// Reads the currently-focused UI element's text plus the foreground app/window identity via
/// Windows UI Automation (UIA3 COM, generated by CsWin32) + Win32, to give the LLM cleanup step
/// context about what the user is looking at when they start dictating.
///
/// CRITICAL privacy rule: if the focused element is a password/secure field
/// (<c>UIA_IsPasswordPropertyId</c> / <c>CurrentIsPassword == true</c>), this class returns "" and
/// never reads any text from it. That check runs before any TextPattern/ValuePattern read.
///
/// UIA is COM/STA and calls are cross-process, so all UIA work runs on a dedicated STA thread with
/// a hard ~2s timeout. Any failure or timeout results in "" — this class never throws.
/// </summary>
public sealed class UiaScreenContextProvider : IScreenContextProvider
{
    private const int MaxSelectedChars = 4096;
    private const int MaxContextChars = 500;

    public Task<string> CaptureContextAsync(CancellationToken ct)
    {
        // UIA is COM/STA and cross-process; run on a dedicated STA thread so a hung or hostile
        // foreground app can never stall the dictation pipeline, and race it against a timeout.
        var tcs = new TaskCompletionSource<string>();

        var thread = new Thread(() =>
        {
            string result;
            try
            {
                result = CaptureCore();
            }
            catch
            {
                result = "";
            }

            tcs.TrySetResult(result);
        })
        {
            IsBackground = true,
        };
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();

        return WaitWithTimeoutAsync(tcs.Task, TimeSpan.FromSeconds(2));
    }

    private static async Task<string> WaitWithTimeoutAsync(Task<string> task, TimeSpan timeout)
    {
        var completed = await Task.WhenAny(task, Task.Delay(timeout)).ConfigureAwait(false);
        if (completed != task)
        {
            // Timed out. The abandoned STA thread is a background thread and finishes (or gets
            // torn down at process exit) on its own later, harmlessly; we never block on it.
            return "";
        }

        try
        {
            return await task.ConfigureAwait(false);
        }
        catch
        {
            return "";
        }
    }

    private static string CaptureCore()
    {
        var (app, title) = ForegroundIdentity();

        string content;
        try
        {
            content = ReadFocusedText(out bool isPassword);
            // NEVER read secure fields: if the focused element is a password field, drop any text
            // and report identity-only context. This check happens before we return content.
            if (isPassword)
            {
                content = "";
            }
        }
        catch
        {
            content = "";
        }

        var s = $"App: {app}\nWindow: {title}\nSelected text: {content}";
        return s.Length > MaxContextChars ? s[..MaxContextChars] : s;
    }

    /// <summary>
    /// Creates the UIA client, gets the focused element, checks IsPassword FIRST, and only reads
    /// text (TextPattern selection, falling back to ValuePattern) when the element is not secure.
    /// </summary>
    private static string ReadFocusedText(out bool isPassword)
    {
        isPassword = false;

        // One-time per (STA) thread; CUIAutomation is a generated COM coclass activated via `new`.
        IUIAutomation automation = (IUIAutomation)new CUIAutomation();
        try
        {
            IUIAutomationElement? focused = automation.GetFocusedElement();
            if (focused is null)
            {
                return "";
            }

            // ---- PASSWORD GUARD (must run before any text read) ----
            // CurrentIsPassword -> Windows BOOL. Non-zero == protected. Fail closed: if we cannot
            // determine the property, treat the element as secure and skip text entirely.
            try
            {
                if (focused.CurrentIsPassword)
                {
                    isPassword = true;
                    return "";
                }
            }
            catch
            {
                isPassword = true;
                return "";
            }

            // Tier A.3: TextPattern selection (multi-line / documents / browsers).
            try
            {
                object patternObj = focused.GetCurrentPattern(UIA_PATTERN_ID.UIA_TextPatternId);
                if (patternObj is IUIAutomationTextPattern textPattern)
                {
                    IUIAutomationTextRangeArray? selection = textPattern.GetSelection();
                    if (selection is not null && selection.Length > 0)
                    {
                        IUIAutomationTextRange range = selection.GetElement(0);
                        string sel = range.GetText(MaxSelectedChars).ToString();
                        if (!string.IsNullOrWhiteSpace(sel))
                        {
                            return sel;
                        }
                    }
                }
            }
            catch
            {
                // Pattern unsupported or cross-process hiccup; fall through to ValuePattern.
            }

            // Tier A.4: ValuePattern (single-line edit controls).
            try
            {
                object patternObj = focused.GetCurrentPattern(UIA_PATTERN_ID.UIA_ValuePatternId);
                if (patternObj is IUIAutomationValuePattern valuePattern)
                {
                    string value = valuePattern.CurrentValue.ToString();
                    if (!string.IsNullOrWhiteSpace(value))
                    {
                        return value;
                    }
                }
            }
            catch
            {
                // Swallow; no text available.
            }

            return "";
        }
        finally
        {
            Marshal.ReleaseComObject(automation);
        }
    }

    private static (string app, string title) ForegroundIdentity()
    {
        try
        {
            HWND hwnd = PInvoke.GetForegroundWindow();
            if (hwnd.IsNull)
            {
                return ("", "");
            }

            // Window title.
            string title = "";
            Span<char> titleBuf = new char[512];
            int len = PInvoke.GetWindowText(hwnd, titleBuf);
            if (len > 0)
            {
                title = new string(titleBuf[..len]);
            }

            // Owning process -> exe basename.
            PInvoke.GetWindowThreadProcessId(hwnd, out uint pid);
            string app = TryGetProcessName(pid);

            return (app, title);
        }
        catch
        {
            return ("", "");
        }
    }

    private static string TryGetProcessName(uint pid)
    {
        if (pid == 0)
        {
            return "";
        }

        try
        {
            using var handle = PInvoke.OpenProcess_SafeHandle(
                PROCESS_ACCESS_RIGHTS.PROCESS_QUERY_LIMITED_INFORMATION, false, pid);
            if (handle.IsInvalid)
            {
                return "";
            }

            Span<char> buf = new char[1024];
            uint size = (uint)buf.Length;
            BOOL ok = PInvoke.QueryFullProcessImageName(
                handle, PROCESS_NAME_FORMAT.PROCESS_NAME_WIN32, buf, ref size);
            if (!ok || size == 0)
            {
                return "";
            }

            string path = new string(buf[..(int)size]);
            return Path.GetFileNameWithoutExtension(path).ToLowerInvariant();
        }
        catch
        {
            return "";
        }
    }
}
